[package]
name = "surway"
version = "0.1.0"
authors = ["Tor Hovland <tor.hovland@bekk.no>"]
edition = "2018"

[dependencies]
cfg-if = "1.0.0"
console_log = { version = "0.2.0", features = ["color"] }
leaflet = "0.1.2"
log = "0.4.14"
quick-xml = { version = "0.20.0", features = ["serialize"] } # 0.21 breaks Trunk debug build.
seed = "0.8.0"
serde = { version = "1.0.123", features = ["derive"] }
wasm-bindgen = { version = "0.2.70", features = ["serde-serialize"] }
web-sys = { version = "0.3.47", features = ["console", "MutationObserver", "MutationObserverInit", "Node"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
