[package]
name = "surway"
version = "0.1.0"
authors = ["Tor Hovland <tor.hovland@bekk.no>"]
edition = "2018"

[dependencies]
cfg-if = "0.1"
console_log = { version = "0.2", features = ["color"] }
leaflet = { git = "https://github.com/torhovland/leaflet-rs" }
log = "0.4"
quick-xml = { version = "0.20", features = ["serialize"] } # 0.21 breaks Trunk debug build.
seed = "0.8"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3", features = ["console", "MutationObserver", "MutationObserverInit", "Node"] }
