on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.conclusion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        uses: docker://torhovland/rust-trunk:0.11.0
        with:
          entrypoint: cargo
          args: test
        env:
          RUSTFLAGS: --cfg=web_sys_unstable_apis

      - name: Build
        uses: docker://torhovland/rust-trunk:0.11.0
        with:
          entrypoint: trunk
          args: --config Trunk-release.toml build
        env:
          RUSTFLAGS: --cfg=web_sys_unstable_apis

      - name: Set branch name
        if: github.event_name == 'pull_request'
        run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Deploy_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: surway.hovland.xyz
          publish_dir: ./dist
          destination_dir: ${{ env.branch_name }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        env:
          CYPRESS_BASE_URL: https://surway.hovland.xyz/${{ env.branch_name }}
        with:
          working-directory: cypress
          spec: cypress/**/*.spec.js

      - name: Save test screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/cypress/screenshots

      - name: Save test videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/cypress/videos
