on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        uses: docker://torhovland/rust-trunk:0.10.0
        run: cargo test

      - name: Build
        uses: docker://torhovland/rust-trunk:0.10.0
        run: trunk --config Trunk-release.toml build

      - name: Get branch name
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Deploy_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: surway.hovland.xyz
          publish_dir: ./dist
          destination_dir: $BRANCH_NAME

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        with:
          working-directory: cypress
          config: baseUrl=https://surway.hovland.xyz/$BRANCH_NAME
          spec: cypress/**/*.spec.js

      - name: Save test screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/cypress/screenshots

      - name: Save test videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/cypress/videos
