on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: torhovland/rust-trunk:0.8.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: trunk --config Trunk-release.toml build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          fqdn: surway.hovland.xyz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
